read:
  replicas: 1
  persistence:
    storageClass: standard

write:
  replicas: 1
  persistence:
    storageClass: standard

backend:
  replicas: 1
  persistence:
    storageClass: standard

loki:
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h
        chunks:
          period: 24h
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
    type: s3
    s3:
      endpoint: http://192.168.49.2:9000
      secretAccessKey: oFQGU2MNLyXqcP2zoUPr62xFylsYTEcnV8wVSieQ
      accessKeyId: xUU2fv3PqPY1qZq9293M
      insecure: true
      s3ForcePathStyle: true
      region: us-east-1

