stages:
  - build_frontend
  - build_backend

frontend:
  stage: build_frontend
  image: docker.arvancloud.ir/docker:latest
  variables:
    DOCKER_IMAGE_NAME: bardiark03/auth-jwt-frontend:v1.0.0
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t $DOCKER_IMAGE_NAME -f ./Backend/Dockerfile .
    - docker push $DOCKER_IMAGE_NAME

backend:
  stage: build_backend
  image: docker.arvancloud.ir/docker:latest
  variables:
    DOCKER_IMAGE_NAME: bardiark03/auth-jwt-backend:v1.0.0
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t $DOCKER_IMAGE_NAME -f ./Frontend/Dockerfile .
    - docker push $DOCKER_IMAGE_NAME
