apiVersion: v1
kind: PersistentVolume
metadata:
  name: s4-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/k8s-storage"
  volumeMode: Filesystem
