apiVersion: batch/v1
kind: Job
metadata:
  name: curl-job
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: curl-container
        image: curlimages/curl:latest
        command: ["curl", "-X", "POST","-H","Authorization: Apikey XXXX","-H","Content-Type: application/json","--data",'{"purge": "all"}', "https://napi.arvancloud.ir/cdn/4.0/domains/arcaptcha.co/caching/purge"]
      restartPolicy: Never
  backoffLimit: 1
