apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx1
  name: nginx1-pod
  namespace: nginx
spec:
  containers:
    - name: nginx-container1
      image: nginx:latest

---

apiVersion: v1
kind: Service
metadata:
  name: nginx1
  namespace: nginx
spec:
  selector:
    app: nginx1
  type: NodePort
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx2
  name: nginx2-pod
  namespace: nginx
spec:
  containers:
    - name: nginx-container2
      image: nginx:latest

---

apiVersion: v1
kind: Service
metadata:
  name: nginx2
  namespace: nginx
spec:
  selector:
    app: nginx2
  type: NodePort
  ports:
  - nodePort: 30003
    port: 80
    targetPort: 80
