apiVersion: v1
data:
  policy.csv: |
    p, role:sync-and-read, applications, get, default/nginx, allow
    p, role:sync-and-read, applications, sync, default/nginx, allow
    g, melika, role:sync-and-read
    g, amir, role:sync
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"policy.csv":"p, role:sync-and-read, applications, get, */*, allow\np, role:sync-and-read, applications, sync, */*, allow\ng, melika, role:sync-and-read\ng, amir, role:sync-and-read\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-02-18T11:55:36Z","labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd","resourceVersion":"3601549","uid":"baaf4500-0c4f-48f7-afbc-47f28b1dd58c"}}
  creationTimestamp: "2025-02-18T11:55:36Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "3602573"
  uid: baaf4500-0c4f-48f7-afbc-47f28b1dd58c
